set session batch_enabled= true;
set session cm_parameter = 2;
set session scheduler_parameter = 4;
set session single_query_cost_threshold = 2;
set session task_concurrency = 32;
set session batch_size = 8;
select count(*) from memory.default.store_sales, memory.default.date_dim where  ss_sold_date_sk=d_date_sk and d_year = 2000;
select count(*) from memory.default.store_sales, memory.default.item, memory.default.store  where ss_item_sk=i_item_sk and ss_store_sk=s_store_sk and i_manager_id >= 50;
select count(*) from memory.default.store_sales, memory.default.item, memory.default.household_demographics  where ss_item_sk=i_item_sk and ss_hdemo_sk=hd_demo_sk and hd_dep_count >=5 and i_manager_id >=50;
select  count(*)  from memory.default.store_sales, memory.default.household_demographics, memory.default.date_dim, memory.default.income_band, memory.default.customer  where ss_hdemo_sk=hd_demo_sk and ss_sold_date_sk=d_date_sk  and ib_income_band_sk = hd_income_band_sk and ss_customer_sk=c_customer_sk and hd_dep_count >=6 and  d_year = 2000;
select count(*) from memory.default.store_sales, memory.default.date_dim, memory.default.item where ss_item_sk=i_item_sk and  ss_sold_date_sk=d_date_sk and d_year = 2000;
select  count(*)  from memory.default.store_sales, memory.default.household_demographics, memory.default.date_dim, memory.default.income_band  where ss_hdemo_sk=hd_demo_sk and ss_sold_date_sk=d_date_sk  and ib_income_band_sk = hd_income_band_sk and hd_dep_count >=6 and d_year = 2000;
select  count(*)  from memory.default.store_sales, memory.default.household_demographics, memory.default.item, memory.default.income_band  where ss_hdemo_sk=hd_demo_sk and ss_item_sk=i_item_sk  and ib_income_band_sk = hd_income_band_sk and hd_dep_count >=6 and i_manager_id >=50;
select  count(*)  from memory.default.store_sales, memory.default.household_demographics, memory.default.income_band, memory.default.customer  where ss_hdemo_sk=hd_demo_sk and ib_income_band_sk = hd_income_band_sk and ss_customer_sk=c_customer_sk and hd_dep_count >=6;
